-- CREATE TABLE IF NOT EXISTS "tags" (
-- 	"id_tag" integer PRIMARY KEY NOT NULL,
-- 	"name" text NOT NULL,
-- 	"color" text NOT NULL,
-- 	CONSTRAINT "tags_name_unique" UNIQUE("name")
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "visits" (
-- 	"id" text PRIMARY KEY NOT NULL,
-- 	"link_id" text NOT NULL,
-- 	"created_at" timestamp NOT NULL,
-- 	"ip" text NOT NULL,
-- 	"user_agent" text NOT NULL
-- );
-- --> statement-breakpoint
-- ALTER TABLE "links" ADD COLUMN "max_visits" integer;--> statement-breakpoint
-- ALTER TABLE "links" ADD COLUMN "available_at" timestamp NOT NULL;--> statement-breakpoint
-- ALTER TABLE "links" ADD COLUMN "expired_at" timestamp;--> statement-breakpoint
-- ALTER TABLE "links" ADD COLUMN "created_at" timestamp NOT NULL;--> statement-breakpoint
-- ALTER TABLE "links" ADD COLUMN "update_at" timestamp NOT NULL;